name: Deploy Web to FTP
on:
  push:
    branches:
      - main
jobs:
  FTP-Deploy-Action:
    name: Deploy to Hosting
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v4

    # SỬA TẠI ĐÂY: Đổi 'frontend' thành 'fontend' để khớp với folder của bạn
    - name: Install and Build Frontend
      run: |
        cd fontend
        npm install
        npm run build 

    # CẬP NHẬT ĐƯỜNG DẪN: Đổi './frontend/dist/' thành './fontend/dist/'
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./fontend/dist/
        server-dir: ./htdocs/